### ISSUE TITLE
FR: Playback queue and Dataview

### ISSUE THREAD

**Issue by javiavid** [travisvn/obsidian-edge-tts#3]
It would be great to be able to read several articles from a playlist.
Maybe you could create a side panel with a playlist and from the right-click obsidian file explorer you could add them.

Another idea could be that it was compatible with dataview.
It would be useful if when you finish reading an article you change the frontmatter to read. You could have a button on the side panel to read all articles without reading or with a dataview query.

**Comment by javiavid** [comment]
Thanks for the response, I think it would be incredible to be able to save articles with Obsidian Clipper and automatically be able to listen to the saved articles while you do other things.

**Comment by travisvn** [comment]
If you are truly interested in functionality like that, I would suggest using the Microsoft Edge web browser, as that is what this project is predicated on. It uses a package that emulates a call, pretending to be the Edge web browser, in order to get free text-to-speech. 

So, I'd have to recommend using the Edge web browser in this case, and I think it would suit your needs well for that scenario

**Comment by javiavid** [comment]
I'll try the suggestion, although I think it would be more interesting to have it in obsidian. Many times you see interesting articles but it is not the time to read them.
This way you could gather them all and "read" them at the same time at the right time.

If it is very complicated to make the dataview query, being able to select several files and add them to a playback queue would also be very interesting.
